# 接受状态
STATUS_ACCEPTED = 1
# 状态错误的答案
STATUS_WRONG_ANSWER = 2
# 超过状态时间限制
STATUS_TIME_LIMIT_EXCEEDED = 3
# 超过状态内存限制
STATUS_MEMORY_LIMIT_EXCEEDED = 4
# 状态运行时错误
STATUS_RUNTIME_ERROR = 6
# 状态编译错误
STATUS_COMPILE_ERROR = 7
# 状态系统错误
STATUS_SYSTEM_ERROR = 8
# 状态判断
STATUS_JUDGING = 20
# 地位编译
STATUS_COMPILING = 21
